"""add inventory histories

Revision ID: b4d8a781064a
Revises: 1cb37288d520
Create Date: 2023-10-08 16:09:29.037526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d8a781064a'
down_revision: Union[str, None] = '1cb37288d520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventories', 'created_at')
    # ### end Alembic commands ###
